# Generated by Django 6.0.6 on 2026-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
